export enum ScreenNames {
  buyAllMetals = 'BuyAllMetals',
  buyPreferences = 'BuyPreferences',
  emailVerification = 'EmailVerification',
  emailVerificationComplete = 'EmailVerificationComplete',
  forgotPassword = 'ForgotPassword',
  home = 'Home',
  login = 'Login',
  modal = 'Modal',
  onboarding = 'Onboarding',
  portfolio = 'Portfolio',
  prices = 'Prices',
  profile = 'Profile',
  resetPasswordComplete = 'ResetPasswordComplete',
  settings = 'Settings',
  signUp = 'SignUp',
  signUpEmailStep = 'SignUpEmailStep',
  signUpNameStep = 'SignUpNameStep',
  signUpPasswordStep = 'SignUpPasswordStep',
  welcome = 'Welcome',
}
